# 1.what is total revenue generated by male vs female customer?
select gender,sum(purchase_amount) as revenue from customer
group by gender;

# 2. which customers used discount still more than avg purchase amount more 
select customer_id,purchase_amount from customer
where discount_applied="Yes" and purchase_amount>= (select avg(purchase_amount) from customer);

# 3.which are top 5 product having highest avg review rating?
select item_purchased,round(avg(review_rating),1) as "Average Review Rating" from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

# 4. compare avg purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

# 5. Do subscriber customer spend more?, compare avg spend and total revenue between subs and non-subs
select subscription_status, count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_revenue from customer
group by subscription_status;

# 6. which 5 product have highest percentage of purchases with discount applied
select item_purchased, round(100 *sum( case when discount_applied='Yes' then 1 else 0 end)/count(*),0) as purchase_percentage from customer
group by item_purchased
order by  purchase_percentage desc limit 5;

# 7. segment customer into new,returning and loyal based on total no. of previous purchases, show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as 'no. of customer' from customer_type
group by customer_segment;

# 8. what are top 3 most purchased product within each category
with item_counts as (
 select category,item_purchased,count(customer_id) as total_orders,
 row_number () over(partition by category order by count(customer_id) desc) as item_rank from customer
 group by category,item_purchased
 )
 
 select item_rank,category,item_purchased,total_orders from item_counts
where item_rank<=3;

# 9. are customer who are repeat buyers(more than 5 prev purchase) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases>5
group by subscription_status;

# 10. what is revenue contribution by each age group 
select age_group, sum(purchase_amount) as total_revenue from customer
group by age_group
order by total_revenue desc

 